### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by DavidS** [hotosm/osm-tasking-manager#85]
Something went wrong here, my original OSMTM.db didn't have a migrate_version table, manually futzing it didn't help much, although I'm pretty sure I've set the right version, since the job_tags table from v6 and the josm_preset column from v7 already exist.

```
(env)root@osmtm:/srv/osmtm/OSMTM# python migration/manage.py upgrade sqlite:///OSMTM.db migration/
[...]
  File "/srv/osmtm/env/lib/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/engine/reflection.py", line 412, in reflecttable
    raise exc.NoSuchTableError(table.name)
migrate.exceptions.DatabaseNotControlledError: migrate_version
(env)root@osmtm:/srv/osmtm/OSMTM# python migration/manage.py version_control sqlite:///OSMTM.db migration/
(env)root@osmtm:/srv/osmtm/OSMTM# sqlite3 OSMTM.db 'UPDATE migrate_version SET version=7;'
(env)root@osmtm:/srv/osmtm/OSMTM# python migration/manage.py upgrade sqlite:///OSMTM.db migration/
7 -> 8... 
Also ensure that you correctly update your data using the script as well
Also ensure that you correctly update your data using the script as well
done
8 -> 9... 
done
9 -> 10... 
done
(env)root@osmtm:/srv/osmtm/OSMTM# python migration/versions/data_upgrade_008.py
1 17855 21400 None 0 1
1 17855 21400 _al 0 2
1 17855 21400 None 1 3
Traceback (most recent call last):
  File "migration/versions/data_upgrade_008.py", line 49, in <module>
    if i.checkout:
AttributeError: 'TileHistory' object has no attribute 'checkout'
(env)root@osmtm:/srv/osmtm/OSMTM# sqlite3 OSMTM.db '.sche tiles_history'
CREATE TABLE tiles_history (
    x INTEGER NOT NULL, 
    y INTEGER NOT NULL, 
    job_id INTEGER NOT NULL, 
    username VARCHAR, 
    "update" DATETIME, 
    checkin INTEGER, 
    comment VARCHAR, 
    version INTEGER NOT NULL, checkout BOOLEAN, change BOOLEAN, zoom INTEGER DEFAULT '1', 
    PRIMARY KEY (x, y, job_id, version)
);
CREATE UNIQUE INDEX tiles_history_pkey ON tiles_history ( x, y, job_id, zoom, version );
(env)root@osmtm:/srv/osmtm/OSMTM# pserve --reload development.ini^C
```

I've also tried running the data_upgrade_008 script with a newer sqlachemy version, but that didn't change a thing. First I was using debian stable's 0.6.3-3+squeeze1, I upgraded to 0.7.2-1~bpo60+2 from the backports.

Note to self: enable reflogs on all production checkouts, so I know which version was deployed before an upgrade.

**Comment by pgiraud** [comment]
The upgrading procedure is really a mess.
I'm so sorry that it's so complicated.

Well, my first thought is that the data_upgrade 008 script is to be used
when upgrading from 7 to 8.
I think you have to migrate form 7 to 8 first, then upgrade the data. Then
you can migrate from 8 to a newer version.
It would have been nice to have the date upgrade included in the migrate
script, but I didn't really find how to do it. Now that there are instance
that I don't control my self, it's becoming a real issue.

I hope you saved your data first.
I should have added a note on how to upgrade.

Where did you find information on how to upgrade?

Pierre

On Sun, Sep 2, 2012 at 2:48 PM, David Schmitt notifications@github.comwrote:

> Something went wrong here, my original OSMTM.db didn't have a
> migrate_version table, manually futzing it didn't help much, although I'm
> pretty sure I've set the right version, since the job_tags table from v6
> and the josm_preset column from v7 already exist.
> 
> (env)root@osmtm:/srv/osmtm/OSMTM# python migration/manage.py upgrade sqlite:///OSMTM.db migration/
> [...]
>   File "/srv/osmtm/env/lib/python2.6/site-packages/SQLAlchemy-0.7.8-py2.6-linux-x86_64.egg/sqlalchemy/engine/reflection.py", line 412, in reflecttable
>     raise exc.NoSuchTableError(table.name)
> migrate.exceptions.DatabaseNotControlledError: migrate_version
> (env)root@osmtm:/srv/osmtm/OSMTM# python migration/manage.py version_control sqlite:///OSMTM.db migration/
> (env)root@osmtm:/srv/osmtm/OSMTM# sqlite3 OSMTM.db 'UPDATE migrate_version SET version=7;'
> (env)root@osmtm:/srv/osmtm/OSMTM# python migration/manage.py upgrade sqlite:///OSMTM.db migration/
> 7 -> 8...
> Also ensure that you correctly update your data using the script as well
> Also ensure that you correctly update your data using the script as well
> done
> 8 -> 9...
> done
> 9 -> 10...
> done
> (env)root@osmtm:/srv/osmtm/OSMTM# python migration/versions/data_upgrade_008.py
> 1 17855 21400 None 0 1
> 1 17855 21400 _al 0 2
> 1 17855 21400 None 1 3
> Traceback (most recent call last):
>   File "migration/versions/data_upgrade_008.py", line 49, in <module>
>     if i.checkout:
> AttributeError: 'TileHistory' object has no attribute 'checkout'
> (env)root@osmtm:/srv/osmtm/OSMTM# sqlite3 OSMTM.db '.sche tiles_history'
> CREATE TABLE tiles_history (
>     x INTEGER NOT NULL,
>     y INTEGER NOT NULL,
>     job_id INTEGER NOT NULL,
>     username VARCHAR,
>     "update" DATETIME,
>     checkin INTEGER,
>     comment VARCHAR,
>     version INTEGER NOT NULL, checkout BOOLEAN, change BOOLEAN, zoom INTEGER DEFAULT '1',
>     PRIMARY KEY (x, y, job_id, version)
> );
> CREATE UNIQUE INDEX tiles_history_pkey ON tiles_history ( x, y, job_id, zoom, version );
> (env)root@osmtm:/srv/osmtm/OSMTM# pserve --reload development.ini^C
> 
> I've also tried running the data_upgrade_008 script with a newer sqlachemy
> version, but that didn't change a thing. First I was using debian stable's
> 0.6.3-3+squeeze1, I upgraded to 0.7.2-1~bpo60+2 from the backports.
> 
> Note to self: enable reflogs on all production checkouts, so I know which
> version was deployed before an upgrade.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pgiraud/OSMTM/issues/85.

## 

Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by DavidS** [comment]
I've followed the instructions in the README.rst, it's quite prominent.

Also, you might note, that I _did_ upgrade 7->10, before running the script.

The two problems were

  1) no migrate_version when starting out
  2) failure on the data_upgrade_008 script

I "fixed" the first my manually creating the table (migrate.py version_control, UPDATE SET version=7), it's all in the log above.

**Comment by DavidS** [comment]
I've added a console as per http://aymanh.com/python-debugging-techniques#launching-an-interactive-console-with-codeinteract and found the following:

```
(env)root@osmtm:/srv/osmtm/OSMTM# python migration/versions/data_upgrade_008.py
1 17855 21400 None 0 1
1 17855 21400 _al 0 2
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> i
<OSMTM.history_meta.TileHistory object at 0x31344d0>
>>> i.__dict__
{'username': u'_al', 'comment': None, '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x3134510>, 'job_id': 1, 'checkin': 0, 'update': datetime.datetime(2012, 7, 26, 15, 48, 36, 584369), 'version': 2, 'y': 21400, 'x': 17855, 'checkout': True}
>>> 
1 17855 21400 None 1 3
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> i.__dict__
{'username': None, 'comment': u'', '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x3134590>, 'job_id': 1, 'checkin': 1, 'update': datetime.datetime(2012, 7, 26, 15, 48, 53, 983175), 'version': 3, 'y': 21400, 'x': 17855}
>>> 
Traceback (most recent call last):
  File "migration/versions/data_upgrade_008.py", line 50, in <module>
    if i.checkout:
AttributeError: 'TileHistory' object has no attribute 'checkout'
(env)root@osmtm:/srv/osmtm/OSMTM# 
```

the last instance really has no checkout attribute. I've experimented with setting all tiles_history.checkouts to False or True, but that didn't help any either...

**Comment by DavidS** [comment]
Aha!

This patch fixes the upgrade script for me:

```
diff --git a/migration/versions/data_upgrade_008.py b/migration/versions/data_upgrade_008.py
index b8bbffd..c5879ab 100644
--- a/migration/versions/data_upgrade_008.py
+++ b/migration/versions/data_upgrade_008.py
@@ -40,7 +40,10 @@ for tile in tiles:

     if i.username:
         i.checkout = True
-            session.add(i)
+        else:
+            i.checkout = False
+
+        session.add(i)

     for ndx, i in enumerate(tiles_history):
     print "%s %s %s %s %s %s" % (i.job_id, i.x, i.y, i.username, i.checkin, i.version)
```

I'm not sure if that's what it _should_ do, so I'm leaving the actual fixing to you. Now off to testing this here.

**Comment by DavidS** [comment]
A few more notes: there is an data_upgrade_010.py that should probably run too. And I had to execute the setup.py again to get pyramid_debugtoolbar (and probably a few other things).

**Comment by DavidS** [comment]
Final note: even after the successful data upgrades, the tm is only marginally functional: It starts loading the tiles, but seems to overload my chromium. You can have a look yourself on http://osmtm.black.co.at/

It seems like openlayers is choking on the ~900 tasks in this job.

**Comment by pgiraud** [comment]
Hi David,

I'm sorry I didn't help you before on this topic.
Did you manage to update your database?

For the final note, can you please send me a copy of your database file?

Thanks,
Pierre

On Sun, Sep 2, 2012 at 10:13 PM, David Schmitt notifications@github.comwrote:

> Final note: even after the successful data upgrades, the tm is only
> marginally functional: It starts loading the tiles, but seems to overload
> my chromium. You can have a look yourself on http://osmtm.black.co.at/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pgiraud/OSMTM/issues/85#issuecomment-8225647.

## 

Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by DavidS** [comment]
I've sent it to your camptocamp address.

**Comment by pgiraud** [comment]
As I can remember, this was fixed.
